"""XMimic training pipeline modules."""

from .envs import BaseEnv, CargoPickupEnv, EnvConfig
from .isaac import CargoPickupIsaacEnv, IsaacEnvConfig
from .rewards import (
    RewardWeights,
    RewardScales,
    RewardTerm,
    HumanXRewardConfig,
    load_reward_config,
    compute_reward_terms,
    compute_total_reward,
)
from .obs import build_mocap_observation, build_nep_observation
from .obs_pipeline import ObservationPipeline, ObservationConfig, ObsField, default_obs_config
from .generalization import (
    GeneralizationConfig,
    disturbed_initialization,
    interaction_termination,
    contact_relative_error,
    should_apply_external_force,
    sample_external_force,
    domain_randomization,
)
from .eval import (
    success_rate,
    generalization_success_rate,
    object_tracking_error,
    key_body_tracking_error,
    sample_generalization,
    build_eval_report,
    save_eval_report,
)
from .train import (
    TeacherConfig,
    train_teacher,
    StudentConfig,
    distill_student,
    train_student_ppo,
    PPOConfig,
    train_ppo,
    load_config,
    save_config,
    save_checkpoint,
    load_checkpoint,
    MultiSkillSampler,
    SkillSample,
)
from .train.physhoi_adapter import ppo_config_from_physhoi, distill_student_with_physhoi
from .mlops import log_metrics
from .contacts import compute_external_torques, solve_contact_forces
from .amp import (
    AMPDiscriminator,
    AMPBatch,
    amp_discriminator_loss,
    amp_reward_from_logits,
    compute_amp_reward,
)
from .controllers import PDController, PDGains, ActionSemantics
from .robot_spec import RobotSpec, load_robot_spec
from .deploy import (
    RuntimeConfig,
    RuntimeLoop,
    TorchPolicy,
    MocapFrame,
    MocapDropout,
    transform_to_robot_frame,
    SafetyConfig,
    SafetyStatus,
    apply_torque_limits,
    safety_check,
)

__all__ = [
    "BaseEnv",
    "CargoPickupEnv",
    "EnvConfig",
    "CargoPickupIsaacEnv",
    "IsaacEnvConfig",
    "RewardWeights",
    "RewardScales",
    "RewardTerm",
    "HumanXRewardConfig",
    "load_reward_config",
    "compute_reward_terms",
    "compute_total_reward",
    "TeacherConfig",
    "train_teacher",
    "StudentConfig",
    "distill_student",
    "train_student_ppo",
    "PPOConfig",
    "train_ppo",
    "load_config",
    "save_config",
    "save_checkpoint",
    "load_checkpoint",
    "MultiSkillSampler",
    "SkillSample",
    "ppo_config_from_physhoi",
    "distill_student_with_physhoi",
    "log_metrics",
    "compute_external_torques",
    "solve_contact_forces",
    "AMPDiscriminator",
    "AMPBatch",
    "amp_discriminator_loss",
    "amp_reward_from_logits",
    "compute_amp_reward",
    "PDController",
    "PDGains",
    "ActionSemantics",
    "RobotSpec",
    "load_robot_spec",
    "RuntimeConfig",
    "RuntimeLoop",
    "TorchPolicy",
    "MocapFrame",
    "MocapDropout",
    "transform_to_robot_frame",
    "SafetyConfig",
    "SafetyStatus",
    "apply_torque_limits",
    "safety_check",
    "build_nep_observation",
    "build_mocap_observation",
    "ObservationPipeline",
    "ObservationConfig",
    "ObsField",
    "default_obs_config",
    "GeneralizationConfig",
    "disturbed_initialization",
    "interaction_termination",
    "contact_relative_error",
    "should_apply_external_force",
    "sample_external_force",
    "domain_randomization",
    "success_rate",
    "generalization_success_rate",
    "object_tracking_error",
    "key_body_tracking_error",
    "sample_generalization",
    "build_eval_report",
    "save_eval_report",
]
